service: geshem

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  memorySize: 128
  timeout: 20
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "s3:*"
          Resource: "arn:aws:s3:::imgs.geshem.space/*"
        - Effect: "Allow"
          Action: "s3:*"
          Resource: "arn:aws:s3:::imgs.geshem.space"

functions:
  update:
    handler: handler.update
    events:
      - schedule: rate(1 minute)

plugins:
  - serverless-python-requirements
